from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy import Column, Integer, Text, Boolean, DateTime, JSON, CheckConstraint, func
from config import get_settings
import pathlib


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, autoincrement=True)
    email = Column(Text, unique=True, nullable=False)
    name = Column(Text, nullable=False)
    password_hash = Column(Text, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    is_superuser = Column(Boolean, default=False, nullable=False)
    force_password_change = Column(Boolean, default=True, nullable=False)
    created_by = Column(Integer, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Conversation(Base):
    __tablename__ = "conversations"
    id = Column(Text, primary_key=True)
    user_id = Column(Integer, nullable=False)
    title = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    # History summarization: generated by the LLM when the conversation exceeds
    # history_turns. Stored here so we don't re-summarize on every turn.
    summary = Column(Text, nullable=True)
    summary_checkpoint = Column(Text, nullable=True)  # message_id of last summarised message


class Message(Base):
    __tablename__ = "messages"
    id = Column(Text, primary_key=True)
    conversation_id = Column(Text, nullable=False)
    role = Column(Text, nullable=False)
    content = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class AuditLog(Base):
    __tablename__ = "audit_log"
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, nullable=True)
    conversation_id = Column(Text, nullable=True)
    question = Column(Text, nullable=True)
    sql_executed = Column(Text, nullable=True)
    outcome = Column(Text, nullable=True)  # executed | blocked | cancelled | failed
    rows_returned = Column(Integer, nullable=True)
    duration_ms = Column(Integer, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class BusinessConfig(Base):
    __tablename__ = "business_config"
    __table_args__ = (CheckConstraint("id = 1", name="singleton"),)
    id = Column(Integer, primary_key=True, default=1)
    business_name = Column(Text, nullable=False)
    business_description = Column(Text, nullable=False)
    db_url_encrypted = Column(Text, nullable=False)
    domain_context = Column(Text, nullable=False)
    business_rules = Column(JSON, nullable=False)        # list[{rule: str}]
    table_descriptions = Column(JSON, nullable=False)    # {table: description}
    kpi_definitions = Column(JSON, nullable=False)       # list[{name, sql, format, icon}]
    starter_questions = Column(JSON, nullable=False)     # list[str]
    explain_cost_threshold = Column(Integer, default=50000, nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


class LLMConfig(Base):
    """Which LLM backend the deployment uses. Singleton (id=1). Superuser-editable."""
    __tablename__ = "llm_config"
    __table_args__ = (CheckConstraint("id = 1", name="singleton_llm"),)
    id = Column(Integer, primary_key=True, default=1)
    provider = Column(Text, nullable=False)            # "azure" | "claude"
    api_key_encrypted = Column(Text, nullable=False)   # Fernet-encrypted
    model = Column(Text, nullable=False)               # Azure: deployment name; Claude: model id
    endpoint = Column(Text, nullable=True)             # Azure only
    api_version = Column(Text, nullable=True)          # Azure only
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


def _make_engine():
    return create_async_engine(get_analytics_db_url(), echo=False)


def get_analytics_db_url() -> str:
    """Single source of truth for the analytics DB URL (app engine + Alembic).

    Prefers ANALYTICS_DB_URL (Postgres in real deployments); falls back to a
    local SQLite file for dev/test when no URL is configured.
    """
    settings = get_settings()
    if settings.analytics_db_url:
        return settings.analytics_db_url
    db_path = pathlib.Path(settings.analytics_db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    return f"sqlite+aiosqlite:///{db_path}"


engine = _make_engine()
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)


async def init_db() -> None:
    """Ensure the schema exists.

    For Postgres (real deployments) the schema is owned by Alembic — run
    `alembic upgrade head`; this is a no-op. For the SQLite dev/test fallback we
    create tables directly for zero-friction local startup.
    """
    if get_analytics_db_url().startswith("sqlite"):
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)


async def get_session() -> AsyncSession:
    async with AsyncSessionLocal() as session:
        yield session
